# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sebsv
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: example
# "service" is the name of this project. This will also be added to your AWS resource names.
service: example

plugins:
  - "@sebsv/sls-ncc"

build:
  esbuild: false

provider:
  name: aws
  runtime: nodejs22.x

functions:
  hello:
    handler: handler.hello

package:
  patterns:
    - "./*.ts"
  individually: true
